package io.septimalmind.baboon.translator.rust

import io.septimalmind.baboon.CompilerTarget.RsTarget
import io.septimalmind.baboon.parser.model.RawMemberMeta
import io.septimalmind.baboon.translator.rust.RsDefnTranslator.{escapeRustTypeName, toSnakeCase}
import io.septimalmind.baboon.typer.BaboonEnquiries
import io.septimalmind.baboon.typer.model.*
import io.septimalmind.baboon.typer.model.TypeRef.AnyVariant
import izumi.fundamentals.platform.strings.TextTree
import izumi.fundamentals.platform.strings.TextTree.*

class RsJsonCodecGenerator(
  trans: RsTypeTranslator,
  target: RsTarget,
  domain: Domain,
  evo: BaboonEvolution,
  enquiries: BaboonEnquiries,
) extends RsCodecTranslator {

  // Reuses the transitive `any` analysis that already drives boxing and Ord derivation,
  // rather than recomputing the same fixpoint here.
  private val representation = new RsFieldRepresentation(domain, evo, trans, enquiries)

  private def bearsAny(id: TypeId): Boolean = id match {
    case u: TypeId.User => representation.containsAny(TypeRef.Scalar(u))
    case _              => false
  }

  override def translate(defn: DomainMember.User, rsRef: RsValue.RsType, srcRef: RsValue.RsType): Option[TextTree[RsValue]] = {
    if (isActive(defn.id)) {
      // For Rust, JSON codecs are handled via serde derive macros on the struct/enum definitions.
      // We don't need separate codec objects like in Scala/C#.
      // The actual serde attributes are generated by RsDefnTranslator.
      // Here we only generate helper methods for programmatic encode/decode.
      defn.defn match {
        case _: Typedef.Dto      => Some(genJsonHelpers(rsRef, defn))
        case _: Typedef.Enum     => Some(genJsonHelpers(rsRef, defn))
        case _: Typedef.Adt      => Some(genJsonHelpers(rsRef, defn))
        case _: Typedef.Foreign  => None
        case _: Typedef.Contract => None
        case _: Typedef.Service  => None
      }
    } else None
  }

  private def genJsonHelpers(name: RsValue.RsType, defn: DomainMember.User): TextTree[RsValue] = {
    q"""impl ${name.asName} {
       |    pub fn to_json(&self) -> Result<String, serde_json::Error> {
       |        serde_json::to_string(self)
       |    }
       |
       |    pub fn to_json_pretty(&self) -> Result<String, serde_json::Error> {
       |        serde_json::to_string_pretty(self)
       |    }
       |
       |    pub fn from_json(s: &str) -> Result<Self, serde_json::Error> {
       |        serde_json::from_str(s)
       |    }
       |
       |    pub fn to_json_value(&self) -> Result<serde_json::Value, serde_json::Error> {
       |        serde_json::to_value(self)
       |    }
       |
       |    pub fn from_json_value(v: serde_json::Value) -> Result<Self, serde_json::Error> {
       |        serde_json::from_value(v)
       |    }
       |
       |    ${ctxEncoder(defn, name).shift(4).trim}
       |}""".stripMargin
  }

  /** Context-carrying JSON encoder, the counterpart of the UEBA side's `encode_ueba(ctx, writer)`.
    *
    * `serde::Serialize` has no room for a codec context, so neither the derive nor the
    * hand-written `Serialize` impls (ADTs, wrapped branches) can reach the facade that an `any`
    * field holding a UEBA payload needs to transcode itself to JSON.
    *
    * Any-bearing types get an explicit field-by-field encoder. Types with no `any` anywhere
    * below them delegate straight to `serde_json::to_value`, so their wire shape is the derive's
    * by construction and cannot drift while the two coexist.
    */
  private def ctxEncoder(defn: DomainMember.User, name: RsValue.RsType): TextTree[RsValue] = {
    val body = if (bearsAny(defn.id)) {
      explicitEncoder(defn, name)
    } else {
      q"""let _ = ctx;
         |serde_json::to_value(self)
         |    .map_err(|e| crate::any_opaque::BaboonCodecError::encoder_failure(format!("{}", e)))""".stripMargin
    }

    q"""/// JSON encode under a codec context. Unlike `to_json_value`, this can transcode `any`
       |/// fields that hold a UEBA payload, provided `ctx` carries a facade.
       |pub fn encode_json(&self, ctx: &crate::baboon_runtime::BaboonCodecContext) -> Result<serde_json::Value, crate::any_opaque::BaboonCodecError> {
       |    ${body.shift(4).trim}
       |}""".stripMargin
  }

  /** Explicit field-by-field JSON encoder for an any-bearing type.
    *
    * Plain leaves still go through `serde_json::to_value`, which is exact by construction — it
    * is what the derive called — while the shapes serde only expressed through field attributes
    * (hex bytes, decimal-as-number, timestamps) are written by the matching `json_tools` helper.
    */
  private def explicitEncoder(defn: DomainMember.User, name: RsValue.RsType): TextTree[RsValue] = {
    defn.defn match {
      case d: Typedef.Dto =>
        val inserts = d.fields.toList.map {
          f =>
            val wireName = f.name.name
            q"""obj.insert("$wireName".to_string(), ${fieldEnc(f.tpe, q"self.${toSnakeCase(f.name.name)}")});"""
        }
        val build = if (inserts.isEmpty) q"" else inserts.joinN()
        q"""let mut obj = serde_json::Map::new();
           |$build
           |Ok(serde_json::Value::Object(obj))""".stripMargin

      case a: Typedef.Adt =>
        val arms = a.dataMembers(domain).toList.map {
          mid =>
            val wireVariantName = mid.name.name.capitalize
            val rsVariantName   = escapeRustTypeName(wireVariantName)
            q"""${name.asName}::$rsVariantName(v) => {
               |    obj.insert("$wireVariantName".to_string(), v.encode_json(ctx)?);
               |}""".stripMargin
        }
        q"""let mut obj = serde_json::Map::new();
           |match self {
           |    ${arms.joinN().shift(4).trim}
           |}
           |Ok(serde_json::Value::Object(obj))""".stripMargin

      case _ => q"""serde_json::to_value(self)
                   |    .map_err(|e| crate::any_opaque::BaboonCodecError::encoder_failure(format!("{}", e)))""".stripMargin
    }
  }

  /** Encoder expression for one field. Recurses through the collection constructors the same way
    * `RsUEBACodecGenerator.mkEncoder` does.
    */
  private def fieldEnc(tpe: TypeRef, ref: TextTree[RsValue]): TextTree[RsValue] = {
    BaboonEnquiries.resolveBaboonRef(tpe, domain, BaboonLang.Rust) match {
      case a: TypeRef.Any =>
        val expectedKind                      = AnyVariant.metaKindByte(a.variant, a.underlying.isDefined)
        val expectedHex                       = "0x%02x".format(expectedKind & 0xFF)
        val (staticDom, staticVer, staticTid) = anyStaticFallbacks(a)
        q"crate::any_opaque::any_field_codec::any_to_json(ctx, ${expectedHex}u8, $staticDom, $staticVer, $staticTid, &$ref)?"

      case TypeRef.Scalar(TypeId.Builtins.bytes) =>
        q"crate::baboon_runtime::json_tools::bytes_to_json(&$ref)"
      case TypeRef.Scalar(TypeId.Builtins.f128) =>
        q"crate::baboon_runtime::json_tools::decimal_to_json(&$ref)"
      case TypeRef.Scalar(TypeId.Builtins.tsu) =>
        q"crate::baboon_runtime::json_tools::tsu_to_json(&$ref)"
      case TypeRef.Scalar(TypeId.Builtins.tso) =>
        q"crate::baboon_runtime::json_tools::tso_to_json(&$ref)"

      case TypeRef.Scalar(_: TypeId.BuiltinScalar) =>
        q"""serde_json::to_value(&$ref).map_err(|e| crate::any_opaque::BaboonCodecError::encoder_failure(format!("{}", e)))?"""

      case TypeRef.Scalar(u: TypeId.User) =>
        domain.defs.meta.nodes.get(u) match {
          // Foreign leaves keep the host type's own serde impl — Baboon cannot know their shape.
          case Some(DomainMember.User(_, _: Typedef.Foreign, _, _)) =>
            q"""serde_json::to_value(&$ref).map_err(|e| crate::any_opaque::BaboonCodecError::encoder_failure(format!("{}", e)))?"""
          case _ =>
            q"$ref.encode_json(ctx)?"
        }

      case c: TypeRef.Constructor =>
        c.id match {
          case TypeId.Builtins.opt =>
            q"""match &$ref {
               |    None => serde_json::Value::Null,
               |    Some(v) => ${fieldEnc(c.args.head, q"(*v)")},
               |}""".stripMargin
          case TypeId.Builtins.lst | TypeId.Builtins.set =>
            q"""{
               |    let mut items = Vec::new();
               |    for item in ($ref).iter() {
               |        items.push(${fieldEnc(c.args.head, q"(*item)")});
               |    }
               |    serde_json::Value::Array(items)
               |}""".stripMargin
          case TypeId.Builtins.map =>
            q"""{
               |    let mut entries = serde_json::Map::new();
               |    for (k, v) in ($ref).iter() {
               |        entries.insert(${mapKeyEnc(c.args.head, q"(*k)")}, ${fieldEnc(c.args.last, q"(*v)")});
               |    }
               |    serde_json::Value::Object(entries)
               |}""".stripMargin
          case o => throw new RuntimeException(s"BUG: Unexpected collection type: $o")
        }
    }
  }

  /** JSON object keys are strings; serde_json coerces map keys the same way. */
  private def mapKeyEnc(tpe: TypeRef, ref: TextTree[RsValue]): TextTree[RsValue] = {
    BaboonEnquiries.resolveBaboonRef(tpe, domain, BaboonLang.Rust) match {
      case TypeRef.Scalar(TypeId.Builtins.str) => q"($ref).clone()"
      case _                                   => q"($ref).to_string()"
    }
  }

  /** Static fallbacks for the cross-format facade helper (`ueba_to_json`). Identical table to
    * `RsUEBACodecGenerator.anyStaticFallbacks` — the wire `meta` may omit components pinned by
    * the field's static declaration, and the facade merges what the codec supplies.
    */
  private def anyStaticFallbacks(a: TypeRef.Any): (TextTree[RsValue], TextTree[RsValue], TextTree[RsValue]) = {
    val none                     = q"None"
    def some(s: String)          = q"""Some("$s")"""
    val currentDomain: String    = domain.id.toString
    val currentDomainVer: String = domain.version.v.toString
    val typeidStatic = a.underlying match {
      case Some(u) => some(u.id.toString)
      case None    => none
    }
    val (domainStatic, versionStatic) = a.variant match {
      case AnyVariant.Global  => (none, none)
      case AnyVariant.ThisDom => (some(currentDomain), none)
      case AnyVariant.Current => (some(currentDomain), some(currentDomainVer))
    }
    (domainStatic, versionStatic, typeidStatic)
  }

  def codecName(name: RsValue.RsType): RsValue.RsType = {
    RsValue.RsType(name.crate, s"${name.name}_JsonCodec", name.fq)
  }

  override def isActive(id: TypeId): Boolean = {
    !BaboonEnquiries.isBaboonRefForeign(id, domain, BaboonLang.Rust) &&
    target.language.generateJsonCodecs && (target.language.generateJsonCodecsByDefault || domain.derivationRequests
      .getOrElse(RawMemberMeta.Derived("json"), Set.empty[TypeId]).contains(id))
  }

  override def id: String = "Json"
}
