package io.septimalmind.baboon.translator.rust

import io.septimalmind.baboon.CompilerTarget.RsTarget
import io.septimalmind.baboon.parser.model.RawMemberMeta
import io.septimalmind.baboon.translator.rust.RsDefnTranslator.{escapeRustTypeName, toSnakeCase}
import io.septimalmind.baboon.typer.BaboonEnquiries
import io.septimalmind.baboon.typer.model.*
import io.septimalmind.baboon.typer.model.TypeRef.AnyVariant
import izumi.fundamentals.platform.strings.TextTree
import izumi.fundamentals.platform.strings.TextTree.*

class RsJsonCodecGenerator(
  target: RsTarget,
  domain: Domain,
) extends RsCodecTranslator {

  override def translate(defn: DomainMember.User, rsRef: RsValue.RsType, srcRef: RsValue.RsType): Option[TextTree[RsValue]] = {
    if (isActive(defn.id)) {
      // For Rust, JSON codecs are handled via serde derive macros on the struct/enum definitions.
      // We don't need separate codec objects like in Scala/C#.
      // The actual serde attributes are generated by RsDefnTranslator.
      // Here we only generate helper methods for programmatic encode/decode.
      defn.defn match {
        case _: Typedef.Dto      => Some(genJsonHelpers(rsRef, defn))
        case _: Typedef.Enum     => Some(genJsonHelpers(rsRef, defn))
        case _: Typedef.Adt      => Some(genJsonHelpers(rsRef, defn))
        case _: Typedef.Foreign  => None
        case _: Typedef.Contract => None
        case _: Typedef.Service  => None
      }
    } else None
  }

  private def genJsonHelpers(name: RsValue.RsType, defn: DomainMember.User): TextTree[RsValue] = {
    q"""impl ${name.asName} {
       |    pub fn to_json(&self) -> Result<String, serde_json::Error> {
       |        serde_json::to_string(self)
       |    }
       |
       |    pub fn to_json_pretty(&self) -> Result<String, serde_json::Error> {
       |        serde_json::to_string_pretty(self)
       |    }
       |
       |    pub fn from_json(s: &str) -> Result<Self, serde_json::Error> {
       |        serde_json::from_str(s)
       |    }
       |
       |    pub fn to_json_value(&self) -> Result<serde_json::Value, serde_json::Error> {
       |        serde_json::to_value(self)
       |    }
       |
       |    pub fn from_json_value(v: serde_json::Value) -> Result<Self, serde_json::Error> {
       |        serde_json::from_value(v)
       |    }
       |
       |    ${ctxEncoder(defn).shift(4).trim}
       |}${anyResolver(defn, name)}""".stripMargin
  }

  /** Context-carrying JSON encoder, the counterpart of the UEBA side's `encode_ueba(ctx, writer)`.
    *
    * `serde::Serialize` has no room for a codec context, so neither the derive nor the
    * hand-written `Serialize` impls (ADTs, wrapped branches) can reach the facade that an `any`
    * field holding a UEBA payload needs to transcode itself to JSON. Rather than re-deriving the
    * whole JSON shape by hand — renames, hex bytes, decimal-as-number, timestamps, user map-key
    * adapters, ADT wrapping — this resolves the `any` slots to their JSON branch first and then
    * lets serde produce the document exactly as it always has.
    *
    * Types with no `any` anywhere below them delegate straight to `serde_json::to_value`, so
    * their wire shape is the derive's by construction and cannot drift.
    */
  private def ctxEncoder(defn: DomainMember.User): TextTree[RsValue] = {
    val body = if (anyBearing.contains(defn.id)) {
      q"""let mut resolved = self.clone();
         |resolved.baboon_resolve_any_for_json(ctx)?;
         |serde_json::to_value(&resolved)
         |    .map_err(|e| crate::any_opaque::BaboonCodecError::encoder_failure(format!("{}", e)))""".stripMargin
    } else {
      q"""let _ = ctx;
         |serde_json::to_value(self)
         |    .map_err(|e| crate::any_opaque::BaboonCodecError::encoder_failure(format!("{}", e)))""".stripMargin
    }

    q"""/// JSON encode under a codec context. Unlike `to_json_value`, this can transcode `any`
       |/// fields that hold a UEBA payload, provided `ctx` carries a facade.
       |pub fn encode_json(&self, ctx: &crate::baboon_runtime::BaboonCodecContext) -> Result<serde_json::Value, crate::any_opaque::BaboonCodecError> {
       |    ${body.shift(4).trim}
       |}""".stripMargin
  }

  /** In-place rewrite of every `any` slot reachable from this value into its JSON branch.
    * Emitted only for any-bearing types; the field site is the only place the per-field static
    * fallbacks and the declared kind byte are known.
    */
  private def anyResolver(defn: DomainMember.User, name: RsValue.RsType): TextTree[RsValue] = {
    if (!anyBearing.contains(defn.id)) return q""

    val body = defn.defn match {
      case d: Typedef.Dto =>
        val steps = d.fields.toList.filter(f => refBearsAny(f.tpe)).map {
          f => resolveStep(f.tpe, q"self.${toSnakeCase(f.name.name)}")
        }
        if (steps.isEmpty) q"Ok(())" else q"""${steps.joinN()}
                                             |Ok(())""".stripMargin

      case a: Typedef.Adt =>
        val arms = a.dataMembers(domain).toList.map {
          mid =>
            val rsVariantName = escapeRustTypeName(mid.name.name.capitalize)
            if (anyBearing.contains(mid)) {
              q"""${name.asName}::$rsVariantName(v) => v.baboon_resolve_any_for_json(ctx),"""
            } else {
              q"""${name.asName}::$rsVariantName(_) => Ok(()),"""
            }
        }
        q"""match self {
           |    ${arms.joinN().shift(4).trim}
           |}""".stripMargin

      case _ => q"Ok(())"
    }

    q"""
       |
       |impl ${name.asName} {
       |    #[doc(hidden)]
       |    pub fn baboon_resolve_any_for_json(&mut self, ctx: &crate::baboon_runtime::BaboonCodecContext) -> Result<(), crate::any_opaque::BaboonCodecError> {
       |        ${body.shift(8).trim}
       |    }
       |}""".stripMargin
  }

  /** Walks `tpe` down to its `any` positions, rewriting each in place. Mirrors the shape of
    * `RsUEBACodecGenerator.mkEncoder`'s recursion over collection constructors.
    */
  private def resolveStep(tpe: TypeRef, ref: TextTree[RsValue]): TextTree[RsValue] = {
    BaboonEnquiries.resolveBaboonRef(tpe, domain, BaboonLang.Rust) match {
      case a: TypeRef.Any =>
        val expectedKind                      = AnyVariant.metaKindByte(a.variant, a.underlying.isDefined)
        val expectedHex                       = "0x%02x".format(expectedKind & 0xFF)
        val (staticDom, staticVer, staticTid) = anyStaticFallbacks(a)
        q"crate::any_opaque::any_field_codec::resolve_any_field_for_json(ctx, ${expectedHex}u8, $staticDom, $staticVer, $staticTid, &mut $ref)?;"

      case TypeRef.Scalar(_) =>
        // A user type that transitively carries `any` — recurse into its own resolver.
        q"$ref.baboon_resolve_any_for_json(ctx)?;"

      case c: TypeRef.Constructor =>
        c.id match {
          case TypeId.Builtins.opt =>
            q"""if let Some(v) = ($ref).as_mut() {
               |    ${resolveStep(c.args.head, q"(*v)").shift(4).trim}
               |}""".stripMargin
          case TypeId.Builtins.lst | TypeId.Builtins.set =>
            q"""for item in ($ref).iter_mut() {
               |    ${resolveStep(c.args.head, q"(*item)").shift(4).trim}
               |}""".stripMargin
          case TypeId.Builtins.map =>
            // Keys are never `any` (the typer rejects it); only values can carry one.
            q"""for (_, v) in ($ref).iter_mut() {
               |    ${resolveStep(c.args.last, q"(*v)").shift(4).trim}
               |}""".stripMargin
          case o => throw new RuntimeException(s"BUG: Unexpected collection type: $o")
        }
    }
  }

  /** Static fallbacks for the cross-format facade helper (`ueba_to_json`). Identical table to
    * `RsUEBACodecGenerator.anyStaticFallbacks` — the wire `meta` may omit components pinned by
    * the field's static declaration, and the facade merges what the codec supplies.
    */
  private def anyStaticFallbacks(a: TypeRef.Any): (TextTree[RsValue], TextTree[RsValue], TextTree[RsValue]) = {
    val none                     = q"None"
    def some(s: String)          = q"""Some("$s")"""
    val currentDomain: String    = domain.id.toString
    val currentDomainVer: String = domain.version.v.toString
    val typeidStatic = a.underlying match {
      case Some(u) => some(u.id.toString)
      case None    => none
    }
    val (domainStatic, versionStatic) = a.variant match {
      case AnyVariant.Global  => (none, none)
      case AnyVariant.ThisDom => (some(currentDomain), none)
      case AnyVariant.Current => (some(currentDomain), some(currentDomainVer))
    }
    (domainStatic, versionStatic, typeidStatic)
  }

  /** Does `tpe` reach an `any` position, either directly or through a user type it references?
    * Drives both which types get a resolver and which fields that resolver has to walk.
    */
  private def refBearsAny(tpe: TypeRef): Boolean = tpe match {
    case _: TypeRef.Any                 => true
    case TypeRef.Scalar(u: TypeId.User) => anyBearing.contains(u)
    case _: TypeRef.Scalar              => false
    case c: TypeRef.Constructor         => c.args.exists(refBearsAny)
  }

  /** Types that carry an `any` somewhere below them, as a least fixpoint over the typespace.
    * Iterative rather than recursive because recursive DTOs (`recursive-ok`) make the reference
    * graph cyclic.
    */
  private lazy val anyBearing: Set[TypeId] = {
    val users = domain.defs.meta.nodes.toList.collect { case (id, u: DomainMember.User) => (id, u) }

    def directAny(tpe: TypeRef): Boolean = tpe match {
      case _: TypeRef.Any         => true
      case _: TypeRef.Scalar      => false
      case c: TypeRef.Constructor => c.args.exists(directAny)
    }

    def userRefs(tpe: TypeRef): List[TypeId] = tpe match {
      case TypeRef.Scalar(u: TypeId.User) => List(u)
      case _: TypeRef.Scalar              => Nil
      case c: TypeRef.Constructor         => c.args.toList.flatMap(userRefs)
      case _: TypeRef.Any                 => Nil // the stored value is an opaque, not the underlying type
    }

    val seeds: Set[TypeId] = users.collect {
      case (id, DomainMember.User(_, d: Typedef.Dto, _, _)) if d.fields.exists(f => directAny(f.tpe)) => id
    }.toSet

    val edges: Map[TypeId, List[TypeId]] = users.map {
      case (id, u) =>
        val refs = u.defn match {
          case d: Typedef.Dto => d.fields.toList.flatMap(f => userRefs(f.tpe))
          case a: Typedef.Adt => a.dataMembers(domain).toList
          case _              => Nil
        }
        (id, refs)
    }.toMap

    Iterator
      .iterate(seeds) {
        current => current ++ edges.collect { case (id, refs) if refs.exists(current.contains) => id }.toSet
      }
      .sliding(2).collectFirst { case Seq(a, b) if a == b => a }
      .getOrElse(seeds)
  }

  def codecName(name: RsValue.RsType): RsValue.RsType = {
    RsValue.RsType(name.crate, s"${name.name}_JsonCodec", name.fq)
  }

  override def isActive(id: TypeId): Boolean = {
    !BaboonEnquiries.isBaboonRefForeign(id, domain, BaboonLang.Rust) &&
    target.language.generateJsonCodecs && (target.language.generateJsonCodecsByDefault || domain.derivationRequests
      .getOrElse(RawMemberMeta.Derived("json"), Set.empty[TypeId]).contains(id))
  }

  override def id: String = "Json"
}
