#!/usr/bin/env bash

set -e

# development script for easy vscode extension testing.
# pairs with .vscode/settings.json

LOCAL_BABOON="./baboon-compiler/.jvm/target/graalvm-native-image/baboon"

if [[ -x "$LOCAL_BABOON" ]]; then
    exec "$LOCAL_BABOON" "$@"
else
    BABOON_BIN="$(nix build .#baboon --print-out-paths --no-link 2>/dev/null)/bin/baboon"
    exec "$BABOON_BIN" baboon "$@"
fi
