// MFACADE-PR-6 stage B (sc): the codegen emits an `object DomainMyOkFacade extends
// BaboonCodecsFacade` per domain that auto-registers every known version in its body
// (via `locally { register(...) }` to dodge -Xsource:3-cross's val _ rejection).
// Generated by `mdl :test-gen-regular-adt`.
package runtime

import baboon.runtime.shared._
import org.scalatest.funsuite.AnyFunSuite

class DomainFacadeSpec extends AnyFunSuite {
  test("DomainMyOkFacade auto-registers and round-trips Inner") {
    val facade = my.ok.DomainMyOkFacade
    val sample = my.ok.Inner(42)

    val encoded = facade.encodeToBin(BaboonCodecContext.Compact, sample)
    assert(encoded.isRight, s"encodeToBin must succeed: $encoded")
    val bytes = encoded.toOption.get

    val decoded = facade.decodeFromBin(bytes)
    assert(decoded.isRight, s"decodeFromBin must succeed: $decoded")
    assert(decoded.toOption.get == sample)
  }
}
