package io.septimalmind.baboon.translator.graphql

import io.septimalmind.baboon.CompilerProduct
import io.septimalmind.baboon.CompilerTarget.GqlTarget
import io.septimalmind.baboon.parser.model.issues.BaboonIssue
import io.septimalmind.baboon.translator.{BaboonAbstractTranslator, OutputFile, Sources}
import io.septimalmind.baboon.typer.model.*
import izumi.functional.bio.{Error2, F}
import izumi.fundamentals.collections.IzCollections.*
import izumi.fundamentals.collections.nonempty.NEList
import io.septimalmind.baboon.parser.model.issues.TranslationIssue

/** Translates Baboon domain models to GraphQL Schema Definition Language (SDL).
  *
  * Emits one `schema.graphql` file per domain version. Schema-only — no codecs,
  * conversions, or runtime are generated.
  *
  * === Type mapping conventions ===
  *
  *  - '''DTO''' → `type`
  *  - '''Enum''' → `enum`
  *  - '''ADT''' → branch DTOs emitted as `type`s, then a `union` over them.
  *    Contracts and services inside ADTs are excluded from the union.
  *  - '''Foreign with `rt`''' → resolved to the underlying Baboon type
  *  - '''Foreign without `rt`''' → emitted as a custom `scalar`
  *  - '''Service / Contract''' → skipped (non-data types)
  *  - '''Type aliases''' → transparent, resolved by the typer before we see them
  *
  * === Scalar mapping ===
  *
  *  - `bit` → `Boolean`, `str` → `String`, `uid` → `ID`
  *  - `i08`/`i16`/`i32`/`u08`/`u16`/`u32` → `Int`
  *  - `f32`/`f64` → `Float`
  *  - `i64` → `BaboonInt64`, `u64` → `BaboonUInt64`, `f128` → `BaboonFloat128`
  *  - `tsu` → `BaboonDateTimeUtc`, `tso` → `BaboonDateTimeOffset`
  *  - `bytes` → `BaboonBytes`
  *
  * Custom scalars (`Baboon*`) are only emitted when actually referenced.
  *
  * === Collection mapping ===
  *
  *  - `opt[T]` → nullable field (no `!` suffix)
  *  - `lst[T]` / `set[T]` → `[T!]!` (non-null list of non-null elements)
  *  - `map[K, V]` → `[BaboonMapEntry_K_V!]!` with a helper type:
  *    {{{type BaboonMapEntry_K_V { key: K!, value: V! }}}}
  *    GraphQL has no native map type so this is the standard workaround.
  *
  * === Limitations ===
  *
  *  - No `Query` root type is emitted — the output is a type-definition library,
  *    not an executable schema.
  *  - Empty DTOs get a placeholder `_empty: Boolean` field (GraphQL forbids
  *    empty object types).
  *  - Narrowing of integer/float widths (e.g. `u08` vs `i32` both → `Int`)
  *    loses precision information at the schema level.
  *  - Field names and enum values are sanitized for GraphQL validity:
  *    names starting with digits get a `_` prefix, `__` prefix is escaped to `gql___`,
  *    and enum values `true`/`false`/`null` get a trailing `_`.
  */
class GqlBaboonTranslator[F[+_, +_]: Error2](
  target: GqlTarget,
  typeTranslator: GqlTypeTranslator,
) extends BaboonAbstractTranslator[F] {

  override def translate(family: BaboonFamily): F[NEList[BaboonIssue], Sources] = {
    for {
      rendered <- F.fromEither {
        val allFiles = family.domains.iterator.flatMap {
          case (_, lineage) =>
            lineage.versions.iterator.map {
              case (_, domain) => translateDomain(domain)
            }
        }.toList

        val flattened = allFiles.flatMap(identity)

        flattened.toUniqueMap(c =>
          BaboonIssue.of(TranslationIssue.NonUniqueOutputFiles(c))
        )
      }
    } yield Sources(rendered)
  }

  private def translateDomain(domain: Domain): List[(String, OutputFile)] = {
    if (!target.output.products.contains(CompilerProduct.Definition)) {
      return List.empty
    }

    val pkg = domain.id
    val ver = domain.version
    val foreignResolutions = typeTranslator.foreignTypeResolution(domain)

    val members = domain.defs.meta.nodes.values.collect {
      case u: DomainMember.User => u
    }.toList.sortBy(_.id.toString)

    // Resolve all field type refs through foreign type mappings
    def resolvedFields(fields: List[Field]): List[Field] = {
      fields.map(f => f.copy(tpe = typeTranslator.resolveTypeRef(f.tpe, foreignResolutions)))
    }

    // Collect all map types used in fields (after resolution) so we can emit helper types
    val allMapTypes = members.flatMap { m =>
      m.defn match {
        case dto: Typedef.Dto =>
          resolvedFields(dto.fields).flatMap(f => typeTranslator.collectMapTypes(f.tpe))
        case _ => Nil
      }
    }.toSet

    // Collect foreign types without runtime mapping — emit as custom scalars
    val foreignScalars = members.flatMap { m =>
      m.defn match {
        case f: Typedef.Foreign if f.runtimeMapping.isEmpty => Some(typeTranslator.typeName(f.id))
        case _ => None
      }
    }.sorted.distinct

    val sb = new StringBuilder
    sb.append(s"# Generated by Baboon compiler\n")
    sb.append(s"# Domain: $pkg, Version: $ver\n\n")

    // Emit custom scalars for builtin overflows
    val builtinCustomScalars = Set(
      "BaboonInt64",
      "BaboonUInt64",
      "BaboonFloat128",
      "BaboonDateTimeUtc",
      "BaboonDateTimeOffset",
      "BaboonBytes",
    )

    val usedScalars = collectUsedCustomScalars(members, foreignResolutions)
    val scalarsToEmit = (builtinCustomScalars.intersect(usedScalars).toList ++ foreignScalars).sorted

    scalarsToEmit.foreach { s =>
      sb.append(s"scalar $s\n")
    }
    if (scalarsToEmit.nonEmpty) sb.append("\n")

    // Emit map entry types (deduplicated by generated name since different TypeRefs can map to the same GraphQL type)
    val mapEntries = allMapTypes.toList.map {
      case (keyRef, valRef) =>
        (typeTranslator.mapEntryTypeName(keyRef, valRef), typeTranslator.fieldTypeStr(keyRef), typeTranslator.fieldTypeStr(valRef))
    }.distinctBy(_._1).sortBy(_._1)

    mapEntries.foreach {
      case (name, keyType, valType) =>
        sb.append(s"type $name {\n")
        sb.append(s"  key: $keyType\n")
        sb.append(s"  value: $valType\n")
        sb.append(s"}\n\n")
    }

    // Emit type definitions (skip ADT-owned types — they are emitted by their parent ADT)
    members.foreach { m =>
      m.defn match {
        case _: Typedef.NonDataTypedef => // skip services, contracts
        case _: Typedef.Foreign        => // skip — handled as scalars or resolved via runtimeMapping
        case _ if m.ownedByAdt         => // skip — emitted by parent ADT
        case defn                      => emitTypedef(sb, defn, domain, foreignResolutions)
      }
    }

    val versionStr = ver.toString.replace(".", "_")
    val pkgStr = pkg.path.toList.map(typeTranslator.sanitize).mkString("_")
    val filename = s"$pkgStr/v$versionStr/schema.graphql"

    List(filename -> OutputFile(sb.toString, CompilerProduct.Definition))
  }

  private def emitTypedef(
    sb: StringBuilder,
    defn: Typedef.User,
    domain: Domain,
    foreignResolutions: Map[TypeId.User, Option[TypeRef]],
  ): Unit = {
    defn match {
      case dto: Typedef.Dto =>
        emitDto(sb, dto, foreignResolutions)

      case e: Typedef.Enum =>
        emitEnum(sb, e)

      case adt: Typedef.Adt =>
        emitAdt(sb, adt, domain, foreignResolutions)

      case _ => // skip
    }
  }

  private def resolveFieldType(ref: TypeRef, foreignResolutions: Map[TypeId.User, Option[TypeRef]]): String = {
    typeTranslator.fieldTypeStr(typeTranslator.resolveTypeRef(ref, foreignResolutions))
  }

  private def emitDto(sb: StringBuilder, dto: Typedef.Dto, foreignResolutions: Map[TypeId.User, Option[TypeRef]]): Unit = {
    val name = typeTranslator.typeName(dto.id)
    if (dto.fields.isEmpty) {
      sb.append(s"type $name {\n")
      sb.append(s"  _empty: Boolean\n")
      sb.append(s"}\n\n")
    } else {
      sb.append(s"type $name {\n")
      dto.fields.foreach { f =>
        sb.append(s"  ${typeTranslator.sanitizeName(f.name.name)}: ${resolveFieldType(f.tpe, foreignResolutions)}\n")
      }
      sb.append(s"}\n\n")
    }
  }

  private def emitEnum(sb: StringBuilder, e: Typedef.Enum): Unit = {
    val name = typeTranslator.typeName(e.id)
    sb.append(s"enum $name {\n")
    e.members.toList.foreach { m =>
      sb.append(s"  ${typeTranslator.sanitizeEnumValue(m.name)}\n")
    }
    sb.append(s"}\n\n")
  }

  private def emitAdt(
    sb: StringBuilder,
    adt: Typedef.Adt,
    domain: Domain,
    foreignResolutions: Map[TypeId.User, Option[TypeRef]],
  ): Unit = {
    import Typedef.Adt.AdtSyntax
    val name = typeTranslator.typeName(adt.id)

    // Only emit data members (skip contracts and services)
    val dataMembers = adt.dataMembers(domain)

    // Emit each branch as a type (Baboon grammar only allows DTOs as ADT branches)
    val branchNames = dataMembers.map { memberId =>
      val branchName = typeTranslator.typeName(memberId)
      domain.defs.meta.nodes.get(memberId).foreach {
        case u: DomainMember.User =>
          u.defn match {
            case dto: Typedef.Dto => emitDto(sb, dto, foreignResolutions)
            case _                => // skip non-DTO members (shouldn't happen per grammar)
          }
        case _ => // skip
      }
      branchName
    }

    sb.append(s"union $name = ${branchNames.mkString(" | ")}\n\n")
  }

  private def collectUsedCustomScalars(
    members: List[DomainMember.User],
    foreignResolutions: Map[TypeId.User, Option[TypeRef]],
  ): Set[String] = {
    members.flatMap { m =>
      m.defn match {
        case dto: Typedef.Dto =>
          dto.fields.flatMap(f => collectScalarsFromRef(typeTranslator.resolveTypeRef(f.tpe, foreignResolutions)))
        case adt: Typedef.Adt =>
          adt.fields.flatMap(f => collectScalarsFromRef(typeTranslator.resolveTypeRef(f.tpe, foreignResolutions)))
        case _ => Nil
      }
    }.toSet
  }

  private def collectScalarsFromRef(ref: TypeRef): Set[String] = {
    ref match {
      case TypeRef.Scalar(id: TypeId.BuiltinScalar) =>
        Set(typeTranslator.scalarName(id)).filter(_.startsWith("Baboon"))
      case TypeRef.Constructor(_, args) =>
        args.toList.flatMap(collectScalarsFromRef).toSet
      case _ =>
        Set.empty
    }
  }
}
