// MFACADE-PR-E (sw): full round-trip test for the auto-emitted DomainMyOkFacade.
//
// Closes the smoke-only constraint set in PR-C: generated DTOs now declare
// `BaboonMetaProvider` conformance (via SwDefnTranslator), and the protocol's default
// extension forwards instance accessors to the per-type static metadata. Result:
// `facade.encodeToBin(ctx, value)` accepts a generated value directly.
// Generated by `mdl :test-gen-regular-adt`.

import XCTest
@testable import BaboonRuntime
@testable import MyOk

final class DomainFacadeTests: XCTestCase {
    func testParameterlessCtor_autoRegisters() throws {
        let facade = DomainMyOkFacade()
        let latest = try facade.latest("my.ok")
        XCTAssertEqual(latest, BaboonVersion(major: 1, minor: 0, patch: 0))
    }

    func testRoundTripsInner_viaFacade() throws {
        let facade = DomainMyOkFacade()
        let sample = Inner(x: 42)

        let encoded = facade.encodeToBin(BaboonCodecContext.compact, sample)
        guard case .success(let bytes) = encoded else {
            XCTFail("encodeToBin must succeed: \(encoded)")
            return
        }

        let decoded = facade.decodeFromBinBytes(bytes)
        guard case .success(let value) = decoded else {
            XCTFail("decodeFromBinBytes must succeed: \(decoded)")
            return
        }

        XCTAssertEqual(value as? Inner, sample)
    }
}
