// MFACADE-PR-6 stage B (sw): smoke test for the auto-emitted DomainMyOkFacade.
//
// Construction proves auto-registration ran without error; full round-trip is exercised
// by the cross-language acceptance harness (mdl :test-acceptance). Direct round-trip
// through the facade requires the generated DTO to conform to `BaboonMetaProvider`, which
// is a separate work item (the runtime surfaces this with an explicit "value of type X
// does not conform to BaboonMetaProvider; generated DTOs gain this conformance in
// PR 9.2/9.3" message). Generated by `mdl :test-gen-regular-adt`.

import XCTest
@testable import BaboonRuntime
@testable import MyOk

final class DomainFacadeTests: XCTestCase {
    func testParameterlessCtor_autoRegisters() throws {
        let facade = DomainMyOkFacade()
        let latest = try facade.latest("my.ok")
        XCTAssertEqual(latest, BaboonVersion(major: 1, minor: 0, patch: 0))
    }
}
