// T45: interface-shape assertions for extracted-contracts-ok (Swift lane).
//
// Exercises the protocol conformance idiom emitted by the Swift backend for the
// my.ok.extracted.contracts fixture (extracted-contracts-ok/).
//
// Three categories per requirement:
//   (a) Contract variant — a concrete type conforming to protocol B is accepted
//       via a `(any B)` existential; its B-declared property is readable through it.
//   (b) Mirror variant — B is a standalone protocol; the host concrete type does
//       NOT conform to it; a probe type DOES.
//   (c) Member-set spot-check — declared protocol properties match documented fields.
//
// All failure paths use unconditional throws — never vacuous unlike Swift's
// `assert(...)` which compiles away under `-O` in release mode.
//
// Run from the codegen'd copy:
//   cd target/test-regular/sw-stub && swift test --filter ExtractedContractsTests
// Generated by `mdl :test-gen-regular-adt`.

import XCTest
import Foundation
@testable import BaboonRuntime
@testable import MyOkExtractedContracts

final class ExtractedContractsTests: XCTestCase {

    // MARK: — helpers

    private enum Fail: Error { case assert(String) }

    private func require(_ condition: Bool, _ message: String) throws {
        if !condition { throw Fail.assert(message) }
    }

    // MARK: — Req 2: IBox (contract) — IntBox + StrBox both conform to IBox

    func testIntBox_conformsToIBox() throws {
        let obj = IntBox(count: 7, item: 42)
        let ref: any IBox = obj
        try require(ref.count == 7, "count through IBox existential must be 7")
    }

    func testStrBox_conformsToIBox_req8() throws {
        let obj = StrBox(count: 3, item: "hello")
        let ref: any IBox = obj
        try require(ref.count == 3, "count through IBox existential on StrBox must be 3 (req 8: >=2 instantiations)")
    }

    func testIBox_memberSet_count() throws {
        // Structural: protocol IBox declares `var count: Int32 { get }`
        let ref: any IBox = IntBox(count: 5, item: 0)
        try require(ref.count == 5, "IBox.count must be readable via existential")
    }

    // MARK: — Req 1: IMirroredPayload (mirror) — standalone; IntPayload does NOT conform

    func testIntPayloadProbe_conformsToIMirroredPayload() throws {
        let obj = IntPayloadProbe(label: "hello")
        let ref: any IMirroredPayload = obj
        try require(ref.label == "hello", "label through IMirroredPayload existential must be 'hello'")
    }

    func testIntPayload_doesNotConformToIMirroredPayload() throws {
        // Mirror contracts are NOT wired onto the host type.
        // IntPayload must NOT conform to IMirroredPayload.
        let obj = IntPayload(label: "x", value: 1)
        let isConforming = obj is any IMirroredPayload
        try require(!isConforming,
            "IntPayload must NOT conform to IMirroredPayload (mirror is standalone, not wired onto host)")
    }

    func testIMirroredPayload_memberSet_label() throws {
        let ref: any IMirroredPayload = IntPayloadProbe(label: "check")
        try require(ref.label == "check", "IMirroredPayload.label must be readable via existential")
    }

    // MARK: — Req 5: ITagged (contract) / ITagMirror (mirror) — multiple clauses

    func testIntTagged_conformsToITagged() throws {
        let obj = IntTagged(label: "t", extra: 5)
        let ref: any ITagged = obj
        try require(ref.label == "t", "label through ITagged existential must be 't'")
    }

    func testIntTagged_doesNotConformToITagMirror() throws {
        let obj = IntTagged(label: "t", extra: 0)
        let isConforming = obj is any ITagMirror
        try require(!isConforming,
            "IntTagged must NOT conform to ITagMirror (mirror is standalone, not wired)")
    }

    func testIntTagMirrorProbe_conformsToITagMirror() throws {
        let obj = IntTagMirrorProbe(label: "m")
        let ref: any ITagMirror = obj
        try require(ref.label == "m", "label through ITagMirror existential must be 'm'")
    }

    func testITagged_memberSet_label() throws {
        let ref: any ITagged = IntTagged(label: "tagcheck", extra: 0)
        try require(ref.label == "tagcheck", "ITagged.label must be readable via existential")
    }

    func testITagMirror_memberSet_label() throws {
        let ref: any ITagMirror = IntTagMirrorProbe(label: "mirrorcheck")
        try require(ref.label == "mirrorcheck", "ITagMirror.label must be readable via existential")
    }

    // MARK: — Req 4: IKey (contract) — templated id host

    func testIntKey_conformsToIKey() throws {
        let obj = IntKey(key: 99, v: 0)
        let ref: any IKey = obj
        try require(ref.key == Int64(99), "key through IKey existential must be 99")
    }

    func testStrKey_conformsToIKey() throws {
        let obj = StrKey(key: 5, v: "x")
        let ref: any IKey = obj
        try require(ref.key == Int64(5), "key through IKey existential on StrKey must be 5 (>=2 instantiations)")
    }

    func testIKey_memberSet_key() throws {
        let ref: any IKey = IntKey(key: 1, v: 0)
        try require(ref.key == Int64(1), "IKey.key must be readable via existential")
    }

    // MARK: — Req 3: IResult (contract) — ADT host

    func testOk_conformsToIResult() throws {
        let obj = IntResult.Ok(tag: "ok", result: 1)
        let ref: any IResult = obj
        try require(ref.tag == "ok", "tag through IResult existential on IntResult.Ok must be 'ok'")
    }

    func testErr_conformsToIResult() throws {
        let obj = IntResult.Err(tag: "err", msg: "oops")
        let ref: any IResult = obj
        try require(ref.tag == "err", "tag through IResult existential on IntResult.Err must be 'err'")
    }

    // MARK: — Req 6: IContainer (contract) — through-parent contribution

    func testIntContainer_conformsToIContainer() throws {
        let obj = IntContainer(own: 10, item: 99, first: 0, second: 20, base_field: 30)
        let ref: any IContainer = obj
        try require(ref.own == 10, "own through IContainer existential must be 10")
        try require(ref.second == 20, "second through IContainer existential must be 20")
        try require(ref.base_field == 30, "base_field through IContainer existential must be 30")
    }

    func testIContainer_memberSet_ownSecondBaseField() throws {
        let ref: any IContainer = IntContainer(own: 1, item: 0, first: 0, second: 2, base_field: 3)
        try require(ref.own == 1, "IContainer.own must be readable via existential")
        try require(ref.second == 2, "IContainer.second must be readable via existential")
        try require(ref.base_field == 3, "IContainer.base_field must be readable via existential")
    }
}
