// Hand-written JSON round-trip test for Custom-foreign map keys (PR-68-D01 fix).
//
// This test exercises the my.ok.m19.foreign fixture (wrapper-around-foreign.baboon):
//   - FStr    — Custom-foreign type; Swift typealias = String
//   - ItemKey — single-field DTO wrapping FStr; used as a map key
//   - Holder  — @root DTO with m: map[ItemKey, str]
//
// Coverage: JSON encode → decode round-trip for Holder where the map key is a
// wrapper DTO (ItemKey) whose single field is a Custom-foreign type (FStr = String).
// The fixed JSON decoder for Holder constructs ItemKey(v: $ref as! FStr) directly
// rather than routing through FStr_JsonCodec (which emits fatalError — the host is
// expected to supply a hand-written implementation for custom-foreign codecs).
//
// NOTE: UEBA round-trips for this fixture are intentionally NOT tested here because
// ItemKey_UebaCodec.encode/decode delegate to FStr_UebaCodec which also emits
// fatalError. UEBA coverage of foreign-keyed maps requires a host-supplied
// FStr_UebaCodec implementation and is out of scope for this fixture's autogenerated
// codecs. Mirrors ForeignMapKeyRoundTripSpec.scala added in PR-66.

import XCTest
import Foundation
@testable import BaboonRuntime
@testable import MyOkM19Foreign

final class ForeignMapKeyRoundTripTests: XCTestCase {

    private let ctx = BaboonCodecContext.compact

    func testHolderWithForeignMapKeys_jsonEncodeDecodeRoundTrip() throws {
        let original = Holder(m: [
            ItemKey(v: "alpha"): "1",
            ItemKey(v: "beta"):  "2",
        ])
        let encoded = Holder_JsonCodec.instance.encode(ctx, original)
        let decoded = try Holder_JsonCodec.instance.decode(ctx, encoded)
        XCTAssertEqual(decoded, original, "JSON round-trip diverged: \(decoded) vs \(original)")
    }

    func testHolderWithEmptyMap_jsonEncodeDecodeRoundTrip() throws {
        let original = Holder(m: [:])
        let encoded = Holder_JsonCodec.instance.encode(ctx, original)
        let decoded = try Holder_JsonCodec.instance.decode(ctx, encoded)
        XCTAssertEqual(decoded, original)
    }

    func testHolderWithSingleEntry_jsonEncodeDecodeRoundTrip() throws {
        let original = Holder(m: [ItemKey(v: "onlyKey"): "onlyValue"])
        let encoded = Holder_JsonCodec.instance.encode(ctx, original)
        let decoded = try Holder_JsonCodec.instance.decode(ctx, encoded)
        XCTAssertEqual(decoded, original)
    }

    func testJsonEncodedShape_keysAreRawStrings() throws {
        // Verify the wire shape: the map is encoded as a JSON object with the
        // foreign type's string value as the key (not a JSON-encoded ItemKey object).
        let original = Holder(m: [ItemKey(v: "myKey"): "myValue"])
        let encoded = Holder_JsonCodec.instance.encode(ctx, original) as! [String: Any]
        let mField = encoded["m"] as! [String: Any]
        XCTAssertEqual(mField.count, 1)
        XCTAssertNotNil(mField["myKey"], "Expected 'myKey' as the wire key; got \(mField.keys)")
        XCTAssertEqual(mField["myKey"] as? String, "myValue")
    }
}
