// MFACADE-PR-6 stage B (jv): the codegen emits a `final class DomainMyOkFacade extends
// BaboonCodecsFacade` per domain that auto-registers every known version in its
// parameterless ctor. Generated by `mdl :test-gen-regular-adt`.
package runtime;

import baboon.runtime.shared.BaboonCodecContext;
import baboon.runtime.shared.BaboonCodecException;
import baboon.runtime.shared.BaboonEither;
import baboon.runtime.shared.BaboonGenerated;
import my.ok.DomainMyOkFacade;
import my.ok.Inner;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;

class DomainFacadeTest {
    @Test
    void parameterlessCtor_autoRegistersAndRoundTripsInner() {
        DomainMyOkFacade facade = new DomainMyOkFacade();
        Inner sample = new Inner(42);

        BaboonEither<BaboonCodecException, byte[]> encoded = facade.encodeToBin(BaboonCodecContext.Compact, sample);
        assertInstanceOf(BaboonEither.Right.class, encoded, "encodeToBin must succeed");
        byte[] bytes = ((BaboonEither.Right<BaboonCodecException, byte[]>) encoded).value();

        BaboonEither<BaboonCodecException, BaboonGenerated> decoded = facade.decodeFromBin(bytes);
        assertInstanceOf(BaboonEither.Right.class, decoded, "decodeFromBin must succeed");
        BaboonGenerated value = ((BaboonEither.Right<BaboonCodecException, BaboonGenerated>) decoded).value();
        assertInstanceOf(Inner.class, value);
        assertEquals(sample, value);
    }
}
