// PR-26.6 (M26) — Java mirror of Scala ForeignMapKeyRoundTripSpec (PR-I.1b-N01).
//
// Round-trip test for the wrapper-around-foreign chain. The fixture is the M19
// my.ok.m19.foreign.baboon model, which defines:
//   - FStr    — Custom-foreign type; Java mapped to java.lang.String
//   - ItemKey — single-field DTO wrapping FStr; usable as a map key
//   - Holder  — @root DTO with m: map[ItemKey, str]
//
// Coverage:
//   1. JSON encode → byte-identity assertion against canonical wire string
//      `{"m":{"alpha":"1","beta":"2"}}` (PR-I-D02 discipline: byte-identity, not
//      structural).
//   2. JSON decode of the canonical wire string → structural equality with the
//      source Holder.
//
// NOTE: UEBA round-trip is intentionally NOT tested here. ItemKey_UEBACodec
// delegates to FStr_UEBACodec which throws IllegalArgumentException("String is
// a foreign type") — the host is expected to supply a hand-written UEBA codec
// for Custom-foreign types. UEBA coverage of foreign-keyed maps requires a
// host-supplied FStr_UEBACodec implementation and is out of scope for this
// fixture's autogenerated codecs. Mirrors the same omission in
// ForeignMapKeyRoundTripTests.swift / ForeignMapKeyRoundTripSpec.scala.
//
// Generated symbols are produced by mdl :test-gen-regular-adt under
// target/test-regular/jv-stub/.
package runtime;

import baboon.runtime.shared.BaboonCodecContext;
import com.fasterxml.jackson.databind.ObjectMapper;
import my.ok.m19.foreign.Holder;
import my.ok.m19.foreign.Holder_JsonCodec;
import my.ok.m19.foreign.ItemKey;
import org.junit.jupiter.api.Test;

import java.util.LinkedHashMap;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class ForeignMapKeyRoundTripTest {

    private final BaboonCodecContext ctx = BaboonCodecContext.Compact;
    private final ObjectMapper mapper = new ObjectMapper();

    @Test
    public void holderWithForeignMapKeysJsonCanonicalWireForm() throws Exception {
        var m = new LinkedHashMap<ItemKey, String>();
        m.put(new ItemKey("alpha"), "1");
        m.put(new ItemKey("beta"), "2");
        var original = new Holder(m);
        var encoded = Holder_JsonCodec.INSTANCE.encode(ctx, original);
        var actual = mapper.writeValueAsString(encoded);
        var expected = "{\"m\":{\"alpha\":\"1\",\"beta\":\"2\"}}";
        assertEquals(expected, actual, "JSON wire form diverged");
    }

    @Test
    public void holderWithForeignMapKeysJsonDecodeStructuralEquality() throws Exception {
        var wire = "{\"m\":{\"alpha\":\"1\",\"beta\":\"2\"}}";
        var node = mapper.readTree(wire);
        var decoded = Holder_JsonCodec.INSTANCE.decode(ctx, node);
        var expectedMap = new LinkedHashMap<ItemKey, String>();
        expectedMap.put(new ItemKey("alpha"), "1");
        expectedMap.put(new ItemKey("beta"), "2");
        var expected = new Holder(expectedMap);
        assertEquals(expected, decoded, "JSON decode round-trip diverged");
    }

    @Test
    public void holderWithEmptyMapJsonRoundTrip() throws Exception {
        var original = new Holder(new LinkedHashMap<>());
        var encoded = Holder_JsonCodec.INSTANCE.encode(ctx, original);
        var decoded = Holder_JsonCodec.INSTANCE.decode(ctx, encoded);
        assertEquals(original, decoded, "empty-map round-trip diverged");
    }
}
