"""D7 / T31 (py): recursive-DTO import + round-trip under Python 3.12.

The generated `recursive.tree.Tree` DTO has self-referential fields
(`left: Optional[Tree]`, `children: list[Tree]`). Pydantic v2 evaluates field
annotations at class-body execution time, so without
`from __future__ import annotations` as the first line of the module the import
raises `NameError: name 'Tree' is not defined`. PyBaboonTranslator.renderTree now
emits that future-import unconditionally (PEP 563), making annotations lazy
strings; this test imports the module (would fail at import on regression) and
round-trips a nested-recursive instance through both the binary and JSON facades.

Generated by `mdl :test-gen-regular-adt` / `:test-gen-wrapped-adt`.
"""

import unittest

from BaboonDefinitions.Generated.baboon_codecs import BaboonCodecContext
from BaboonDefinitions.Generated.recursive.tree.Tree import Tree
from BaboonDefinitions.Generated.recursive.tree.domain_facade import DomainRecursiveTreeFacade


class RecursiveTreeRoundTripTest(unittest.TestCase):
    @staticmethod
    def _sample() -> Tree:
        # Exercise both recursive field kinds: nullable self-ref `left` and the
        # heap-backed list of self-refs `children`, nested several levels deep.
        leaf = Tree(value=3, left=None, children=[])
        mid = Tree(value=2, left=leaf, children=[Tree(value=4, left=None, children=[])])
        return Tree(value=1, left=mid, children=[leaf, mid])

    def test_round_trips_recursive_tree_bin(self):
        facade = DomainRecursiveTreeFacade()
        sample = self._sample()
        encoded = facade.encode_to_bin(BaboonCodecContext.Compact, sample)
        decoded = facade.decode_from_bin_bytes(encoded)
        self.assertEqual(decoded, sample)

    def test_round_trips_recursive_tree_json(self):
        facade = DomainRecursiveTreeFacade()
        sample = self._sample()
        encoded = facade.encode_to_json(sample)
        decoded = facade.decode_from_json(encoded)
        self.assertEqual(decoded, sample)


if __name__ == "__main__":
    unittest.main()
