"""MFACADE-PR-6 stage B (py): the codegen emits a `DomainMyOkFacade(BaboonCodecsFacade)`
per domain that auto-registers every known version in `__init__`.
Generated by `mdl :test-gen-regular-adt`."""

import unittest

from BaboonDefinitions.Generated.baboon_codecs import BaboonCodecContext
from BaboonDefinitions.Generated.my.ok.Inner import Inner
from BaboonDefinitions.Generated.my.ok.domain_facade import DomainMyOkFacade


class DomainFacadeTest(unittest.TestCase):
    def test_round_trips_inner(self):
        facade = DomainMyOkFacade()
        sample = Inner(x=42)
        encoded = facade.encode_to_bin(BaboonCodecContext.Compact, sample)
        decoded = facade.decode_from_bin_bytes(encoded)
        self.assertEqual(decoded, sample)


if __name__ == "__main__":
    unittest.main()
