//addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings" % "1.1.1")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.12.0")
addSbtPlugin("io.7mind.izumi.sbt" % "sbt-izumi" % "0.0.121")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.22.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.4.0")
