// swift-tools-version: 5.9
import PackageDescription

// PR-68 (M23.4): Swift SPM cannot share basenames across files in a single
// flat .testTarget(); the auto-mangled .o filenames collide (`holder_test.swift`
// in MyOkM19Direct vs MyOkM19Foreign etc.) and the build fails with
// "multiple producers" before any compilation begins. Splitting into one
// .testTarget() per Tests/BaboonTests/<Module>/ subdirectory gives each
// generated test file its own Swift module, so the .o filenames live under
// disjoint module-scoped build dirs.
//
// Hand-written runtime tests live under Tests/RuntimeTests/ to keep
// Tests/BaboonTests/ purely codegen-owned (the rsync action treats it as
// regenerable).
//
// CrossLanguageFixturePath.swift, emitted by codegen at the top of
// Tests/BaboonTests/, is copied into each per-module subdirectory by the
// test-gen-{regular,wrapped}-adt mdl actions (see .mdl/defs/tests.md). Each
// per-module test target then compiles its own copy alongside the generated
// tests as if both files belonged to the same module — matching the
// codegen-emitted test files' expectation that helpers are top-level free
// functions in the current module (no `import` line).

let package = Package(
    name: "BaboonSwiftTests",
    platforms: [.macOS(.v13)],
    targets: [
        // ----- Runtime --------------------------------------------------------------------------
        .target(
            name: "BaboonRuntime",
            path: "Sources/BaboonRuntime"
        ),

        // ----- testpkg.pkg0 evolution chain (v1.0.0 → v2.0.0 → current) -------------------------
        .target(
            name: "TestpkgPkg0_v1_0_0",
            dependencies: ["BaboonRuntime"],
            path: "Sources/TestpkgPkg0_v1_0_0"
        ),
        .target(
            name: "TestpkgPkg0_v2_0_0",
            dependencies: ["BaboonRuntime", "TestpkgPkg0_v1_0_0"],
            path: "Sources/TestpkgPkg0_v2_0_0"
        ),
        .target(
            name: "TestpkgPkg0",
            dependencies: ["BaboonRuntime", "TestpkgPkg0_v1_0_0", "TestpkgPkg0_v2_0_0"],
            path: "Sources/TestpkgPkg0"
        ),

        // ----- rename.ns evolution chain --------------------------------------------------------
        .target(
            name: "RenameNs_v1_0_0",
            dependencies: ["BaboonRuntime"],
            path: "Sources/RenameNs_v1_0_0"
        ),
        .target(
            name: "RenameNs",
            dependencies: ["BaboonRuntime", "RenameNs_v1_0_0"],
            path: "Sources/RenameNs"
        ),

        // ----- Single-version fixtures ----------------------------------------------------------
        .target(
            name: "MyOk",
            dependencies: ["BaboonRuntime"],
            path: "Sources/MyOk"
        ),
        .target(
            name: "IdentifierOk",
            dependencies: ["BaboonRuntime"],
            path: "Sources/IdentifierOk"
        ),
        .target(
            name: "MyOkIdcontracts",
            dependencies: ["BaboonRuntime"],
            path: "Sources/MyOkIdcontracts"
        ),

        // ----- M19 (identifier-and-contract evolution) fixtures ---------------------------------
        .target(
            name: "MyOkM19Alias",
            dependencies: ["BaboonRuntime"],
            path: "Sources/MyOkM19Alias"
        ),
        .target(
            name: "MyOkM19Direct",
            dependencies: ["BaboonRuntime"],
            path: "Sources/MyOkM19Direct"
        ),
        .target(
            name: "MyOkM19Foreign",
            dependencies: ["BaboonRuntime"],
            path: "Sources/MyOkM19Foreign"
        ),
        // NOTE: Tests/BaboonTests/MyOkM19Foreign/ is not auto-generated by codegen
        // because SwCodecFixtureTranslator/SwCodecTestsTranslator exclude types that
        // transitively contain Custom-foreign types (the ItemKey.v field is FStr, a
        // Custom-foreign, and ItemKey_JsonCodec.decode / ItemKey_UebaCodec.encode/decode
        // delegate to the foreign codec's fatalError stub). The JSON round-trip for
        // Holder (which uses ItemKey only as a map key, bypassing the foreign codec
        // in field-value position) is covered by the hand-written ForeignMapKeyRoundTripTests
        // in Tests/RuntimeTests/ — see PR-68-D02.
        .target(
            name: "MyOkM19Multiid",
            dependencies: ["BaboonRuntime"],
            path: "Sources/MyOkM19Multiid"
        ),
        .target(
            name: "MyOkM19Nested",
            dependencies: ["BaboonRuntime"],
            path: "Sources/MyOkM19Nested"
        ),
        .target(
            name: "MyOkM19Singleid",
            dependencies: ["BaboonRuntime"],
            path: "Sources/MyOkM19Singleid"
        ),

        // ----- M20 (ADT branch inheritance) fixtures --------------------------------------------
        .target(
            name: "MyOkM20Chained",
            dependencies: ["BaboonRuntime"],
            path: "Sources/MyOkM20Chained"
        ),
        .target(
            name: "MyOkM20Equiv",
            dependencies: ["BaboonRuntime"],
            path: "Sources/MyOkM20Equiv"
        ),
        .target(
            name: "MyOkM20Equivmanual",
            dependencies: ["BaboonRuntime"],
            path: "Sources/MyOkM20Equivmanual"
        ),
        .target(
            name: "MyOkM20Equivsugared",
            dependencies: ["BaboonRuntime"],
            path: "Sources/MyOkM20Equivsugared"
        ),
        .target(
            name: "MyOkM20Exclude",
            dependencies: ["BaboonRuntime"],
            path: "Sources/MyOkM20Exclude"
        ),
        .target(
            name: "MyOkM20Intersect",
            dependencies: ["BaboonRuntime"],
            path: "Sources/MyOkM20Intersect"
        ),
        .target(
            name: "MyOkM20Nsqual",
            dependencies: ["BaboonRuntime"],
            path: "Sources/MyOkM20Nsqual"
        ),
        .target(
            name: "MyOkM20Simple",
            dependencies: ["BaboonRuntime"],
            path: "Sources/MyOkM20Simple"
        ),

        // ----- mcp.stub (T22 fixture; recursive DTO `Tree`) -------------------------------------
        // T23 / D8: wired into the Swift matrix so the recursive value-type DTO `Tree`
        // (`left: opt[Tree]`, boxed behind `@BaboonIndirect`) is compiled AND round-tripped.
        // Before T23 the generated McpStub module failed `swift build` (infinite-size struct),
        // so the stub package omitted it; it is included now that struct recursion is fixed.
        .target(
            name: "McpStub",
            dependencies: ["BaboonRuntime"],
            path: "Sources/McpStub"
        ),

        // ----- Hand-written runtime tests -------------------------------------------------------
        // AnyMetaCodecTests / AnyRoundTripTests / IdentifierReprTests live under
        // Tests/RuntimeTests/ to keep the codegen-owned Tests/BaboonTests/ tree pristine.
        // AnyRoundTripTests imports MyOk; IdentifierReprTests imports IdentifierOk.
        .testTarget(
            name: "RuntimeTests",
            dependencies: ["BaboonRuntime", "MyOk", "IdentifierOk", "MyOkM19Foreign", "TestpkgPkg0", "McpStub"],
            path: "Tests/RuntimeTests"
        ),

        // ----- Per-module codegen test targets --------------------------------------------------
        // Each .testTarget(name: "<X>Tests", path: "Tests/BaboonTests/<X>") is its own Swift
        // module, so generated `*_test.swift` files can share basenames across modules without
        // .o filename collisions. The dependency on the corresponding source target satisfies
        // each test's `@testable import <X>`. CrossLanguageFixturePath.swift is materialized
        // into each subdirectory by the mdl test-gen action.
        .testTarget(
            name: "IdentifierOkTests",
            dependencies: ["BaboonRuntime", "IdentifierOk"],
            path: "Tests/BaboonTests/IdentifierOk"
        ),
        .testTarget(
            name: "MyOkTests",
            dependencies: ["BaboonRuntime", "MyOk"],
            path: "Tests/BaboonTests/MyOk"
        ),
        .testTarget(
            name: "MyOkIdcontractsTests",
            dependencies: ["BaboonRuntime", "MyOkIdcontracts"],
            path: "Tests/BaboonTests/MyOkIdcontracts"
        ),
        .testTarget(
            name: "MyOkM19AliasTests",
            dependencies: ["BaboonRuntime", "MyOkM19Alias"],
            path: "Tests/BaboonTests/MyOkM19Alias"
        ),
        .testTarget(
            name: "MyOkM19DirectTests",
            dependencies: ["BaboonRuntime", "MyOkM19Direct"],
            path: "Tests/BaboonTests/MyOkM19Direct"
        ),
        .testTarget(
            name: "MyOkM19MultiidTests",
            dependencies: ["BaboonRuntime", "MyOkM19Multiid"],
            path: "Tests/BaboonTests/MyOkM19Multiid"
        ),
        .testTarget(
            name: "MyOkM19NestedTests",
            dependencies: ["BaboonRuntime", "MyOkM19Nested"],
            path: "Tests/BaboonTests/MyOkM19Nested"
        ),
        .testTarget(
            name: "MyOkM19SingleidTests",
            dependencies: ["BaboonRuntime", "MyOkM19Singleid"],
            path: "Tests/BaboonTests/MyOkM19Singleid"
        ),
        .testTarget(
            name: "MyOkM20ChainedTests",
            dependencies: ["BaboonRuntime", "MyOkM20Chained"],
            path: "Tests/BaboonTests/MyOkM20Chained"
        ),
        .testTarget(
            name: "MyOkM20EquivTests",
            dependencies: ["BaboonRuntime", "MyOkM20Equiv"],
            path: "Tests/BaboonTests/MyOkM20Equiv"
        ),
        .testTarget(
            name: "MyOkM20EquivmanualTests",
            dependencies: ["BaboonRuntime", "MyOkM20Equivmanual"],
            path: "Tests/BaboonTests/MyOkM20Equivmanual"
        ),
        .testTarget(
            name: "MyOkM20EquivsugaredTests",
            dependencies: ["BaboonRuntime", "MyOkM20Equivsugared"],
            path: "Tests/BaboonTests/MyOkM20Equivsugared"
        ),
        .testTarget(
            name: "MyOkM20ExcludeTests",
            dependencies: ["BaboonRuntime", "MyOkM20Exclude"],
            path: "Tests/BaboonTests/MyOkM20Exclude"
        ),
        .testTarget(
            name: "MyOkM20IntersectTests",
            dependencies: ["BaboonRuntime", "MyOkM20Intersect"],
            path: "Tests/BaboonTests/MyOkM20Intersect"
        ),
        .testTarget(
            name: "MyOkM20NsqualTests",
            dependencies: ["BaboonRuntime", "MyOkM20Nsqual"],
            path: "Tests/BaboonTests/MyOkM20Nsqual"
        ),
        .testTarget(
            name: "MyOkM20SimpleTests",
            dependencies: ["BaboonRuntime", "MyOkM20Simple"],
            path: "Tests/BaboonTests/MyOkM20Simple"
        ),
        .testTarget(
            name: "RenameNsTests",
            dependencies: ["BaboonRuntime", "RenameNs"],
            path: "Tests/BaboonTests/RenameNs"
        ),
        .testTarget(
            name: "TestpkgPkg0Tests",
            dependencies: ["BaboonRuntime", "TestpkgPkg0"],
            path: "Tests/BaboonTests/TestpkgPkg0"
        ),
    ]
)
