// MFACADE-PR-6 stage B (kt): the codegen emits a `class DomainMyOkFacade : BaboonCodecsFacade()`
// per domain that auto-registers every known version in `init`. Generated by
// `mdl :test-gen-regular-adt`.
package runtime

import baboon.runtime.shared.BaboonCodecContext
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class DomainFacadeTest {
    @Test
    fun parameterlessCtor_autoRegistersAndRoundTripsInner() {
        val facade = my.ok.DomainMyOkFacade()
        val sample = my.ok.Inner(42)

        val bytes = facade.encodeToBin(BaboonCodecContext.Compact, sample)
        val decoded = facade.decodeFromBin(bytes)
        assertEquals(sample, decoded)
    }
}
