// PR-26.6 (M26) — Kotlin mirror of Scala ForeignMapKeyRoundTripSpec (PR-I.1b-N01).
//
// Round-trip test for the wrapper-around-foreign chain. The fixture is the M19
// my.ok.m19.foreign.baboon model, which defines:
//   - FStr    — Custom-foreign type; Kotlin mapped to kotlin.String
//   - ItemKey — single-field DTO wrapping FStr; usable as a map key
//   - Holder  — @root DTO with m: map[ItemKey, str]
//
// Coverage:
//   1. JSON encode → byte-identity assertion against canonical wire string
//      `{"m":{"alpha":"1","beta":"2"}}` (PR-I-D02 discipline: byte-identity, not
//      structural).
//   2. JSON decode of the canonical wire string → structural equality with the
//      source Holder.
//
// NOTE: UEBA round-trip is intentionally NOT tested here. ItemKey_UEBACodec
// delegates to FStr_UEBACodec which throws IllegalArgumentException("String is
// a foreign type") — the host is expected to supply a hand-written UEBA codec
// for Custom-foreign types. UEBA coverage of foreign-keyed maps requires a
// host-supplied FStr_UEBACodec implementation and is out of scope for this
// fixture's autogenerated codecs. Mirrors the same omission in
// ForeignMapKeyRoundTripTests.swift / ForeignMapKeyRoundTripSpec.scala.
//
// Generated symbols are produced by mdl :test-gen-regular-adt under
// target/test-regular/kt-stub/.
package runtime

import baboon.runtime.shared.BaboonCodecContext
import kotlinx.serialization.json.Json
import my.ok.m19.foreign.Holder
import my.ok.m19.foreign.Holder_JsonCodec
import my.ok.m19.foreign.ItemKey
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class ForeignMapKeyRoundTripTest {

    private val ctx = BaboonCodecContext.Compact

    @Test
    fun holderWithForeignMapKeysJsonCanonicalWireForm() {
        val original = Holder(
            m = linkedMapOf(
                ItemKey("alpha") to "1",
                ItemKey("beta") to "2",
            )
        )
        val encoded = Holder_JsonCodec.encode(ctx, original)
        val expected = """{"m":{"alpha":"1","beta":"2"}}"""
        assertEquals(expected, encoded.toString(), "JSON wire form diverged")
    }

    @Test
    fun holderWithForeignMapKeysJsonDecodeStructuralEquality() {
        val wire = """{"m":{"alpha":"1","beta":"2"}}"""
        val node = Json.parseToJsonElement(wire)
        val decoded = Holder_JsonCodec.decode(ctx, node)
        val expected = Holder(
            m = linkedMapOf(
                ItemKey("alpha") to "1",
                ItemKey("beta") to "2",
            )
        )
        assertEquals(expected, decoded, "JSON decode round-trip diverged")
    }

    @Test
    fun holderWithEmptyMapJsonRoundTrip() {
        val original = Holder(m = emptyMap())
        val encoded = Holder_JsonCodec.encode(ctx, original)
        val decoded = Holder_JsonCodec.decode(ctx, encoded)
        assertEquals(original, decoded, "empty-map round-trip diverged")
    }
}
