// MFACADE-PR-6 stage B (dt): smoke test for the auto-emitted DomainMyOkFacade.
// Construction proves auto-registration runs without error; full round-trip is exercised
// by the cross-language acceptance harness (mdl :test-acceptance).
//
// Note: full round-trip via the facade requires generated DTOs to implement
// `BaboonMetaProvider`. PR-E attempted that conformance and discovered Dart's hard
// constraint that a class cannot have both static and instance members of the same name —
// the codegen's `static const String baboonDomainVersion = '...'` and the proposed
// instance getter `String get baboonDomainVersion => ...` collide. Closing the gap needs
// a separate codegen restructure (e.g., move the static fields to a companion class so
// the DTO itself only carries instance accessors). Tracked in defects.md.
//
// Generated by `mdl :test-gen-regular-adt`.

import 'package:baboon_runtime/baboon_codecs_facade.dart';
import 'package:test/test.dart';

import '../../lib/my/ok/domain_my_ok_facade.dart';

void main() {
  test('DomainMyOkFacade ctor runs without error', () {
    final facade = DomainMyOkFacade();
    expect(facade, isA<BaboonCodecsFacade>());
    // Auto-registration of `my.ok/1.0.0` succeeded if `latest()` resolves.
    expect(facade.latest('my.ok'), isNotNull);
  });
}
