// MFACADE-PR-F (dt): full round-trip test for the auto-emitted DomainMyOkFacade.
//
// Generated DTOs/Enums/ADTs now implement `BaboonMetaProvider` (via DtDefnTranslator)
// after the per-DTO static metadata fields were renamed with a `Const` suffix to dodge
// Dart's same-name static-vs-instance restriction. Result: `facade.encodeToBin(ctx, value)`
// accepts a generated value directly, same as cs/sc/jv/kt/kt-kmp/py/ts.
//
// Generated by `mdl :test-gen-regular-adt`.

import 'package:baboon_runtime/baboon_codecs_facade.dart';
import 'package:baboon_runtime/baboon_runtime.dart';
import 'package:test/test.dart';

import '../../lib/my/ok/domain_my_ok_facade.dart';
import '../../lib/my/ok/inner.dart';

void main() {
  test('DomainMyOkFacade ctor runs without error', () {
    final facade = DomainMyOkFacade();
    expect(facade, isA<BaboonCodecsFacade>());
    // Auto-registration of `my.ok/1.0.0` succeeded if `latest()` resolves.
    expect(facade.latest('my.ok'), isNotNull);
  });

  test('DomainMyOkFacade round-trips Inner via the facade', () {
    final facade = DomainMyOkFacade();
    final sample = Inner(x: 42);

    final encoded = facade.encodeToBin(BaboonCodecContext.compact, sample);
    expect(encoded, isA<BaboonRight<BaboonCodecException, dynamic>>());
    final bytes = (encoded as BaboonRight<BaboonCodecException, dynamic>).value;

    final decoded = facade.decodeFromBinBytes(bytes);
    expect(decoded, isA<BaboonRight<BaboonCodecException, BaboonGenerated>>());
    final value = (decoded as BaboonRight<BaboonCodecException, BaboonGenerated>).value;

    expect(value, equals(sample));
  });
}
