// MFACADE-PR-6 stage B (dt): smoke test for the auto-emitted DomainMyOkFacade.
// Construction proves auto-registration runs without error; full round-trip is exercised
// by the cross-language acceptance harness (mdl :test-acceptance).
//
// Generated by `mdl :test-gen-regular-adt`.

import 'package:baboon_runtime/baboon_codecs_facade.dart';
import 'package:test/test.dart';

import '../../lib/my/ok/domain_my_ok_facade.dart';

void main() {
  test('DomainMyOkFacade ctor runs without error', () {
    final facade = DomainMyOkFacade();
    expect(facade, isA<BaboonCodecsFacade>());
    // Auto-registration of `my.ok/1.0.0` succeeded if `latest()` resolves.
    expect(facade.latest('my.ok'), isNotNull);
  });
}
