// T45: interface-shape assertions for extracted-contracts-ok (Dart lane).
//
// Exercises the abstract-interface / implements contract idiom emitted by the
// Dart backend for the my.ok.extracted.contracts fixture.
//
// Three categories per requirement:
//   (a) Contract variant — a concrete type that implements B is accepted through
//       a B-typed variable and its B-declared getter is readable via that ref.
//   (b) Mirror variant — B exists as a standalone abstract interface; the host
//       concrete type does NOT implement it; a probe type DOES.
//   (c) Member-set spot-check — declared getters match documented fields.
//
// All failure paths throw unconditionally.  Dart's `assert` is vacuous in
// release mode, so every check uses explicit `throw`.
//
// Run from the codegen'd copy:
//   cd target/test-regular/dt-stub && dart test test/runtime/extracted_contracts_test.dart
// Generated by `mdl :test-gen-regular-adt`.

import 'package:test/test.dart';

import '../../lib/my/ok/extracted/contracts/i_box.dart';
import '../../lib/my/ok/extracted/contracts/i_mirrored_payload.dart';
import '../../lib/my/ok/extracted/contracts/i_tagged.dart';
import '../../lib/my/ok/extracted/contracts/i_tag_mirror.dart';
import '../../lib/my/ok/extracted/contracts/i_key.dart';
import '../../lib/my/ok/extracted/contracts/i_result.dart';
import '../../lib/my/ok/extracted/contracts/i_container.dart';
import '../../lib/my/ok/extracted/contracts/int_box.dart';
import '../../lib/my/ok/extracted/contracts/str_box.dart';
import '../../lib/my/ok/extracted/contracts/int_payload.dart';
import '../../lib/my/ok/extracted/contracts/int_payload_probe.dart';
import '../../lib/my/ok/extracted/contracts/int_tagged.dart';
import '../../lib/my/ok/extracted/contracts/int_tag_mirror_probe.dart';
import '../../lib/my/ok/extracted/contracts/int_key.dart';
import '../../lib/my/ok/extracted/contracts/str_key.dart';
import '../../lib/my/ok/extracted/contracts/int_result.dart';
import '../../lib/my/ok/extracted/contracts/int_container.dart';

/// Unconditional throw — never vacuous unlike Dart release-mode `assert`.
void require(bool condition, String message) {
  if (!condition) throw StateError(message);
}

void main() {
  // ── Req 2: IBox (contract) — IntBox + StrBox both implement IBox ──────────

  group('IBox contract', () {
    test('IntBox is an IBox', () {
      // Upcast to Object before `is` to avoid unnecessary_type_check warning.
      final Object obj = IntBox(count: 7, item: 42);
      require(obj is IBox, 'IntBox must implement IBox');
    });

    test('IntBox count readable through IBox-typed reference', () {
      final IBox ref = IntBox(count: 7, item: 42);
      require(ref.count == 7, 'count through IBox ref must be 7');
    });

    test('StrBox also implements IBox (req 8: >=2 instantiations)', () {
      // Upcast to Object before `is` to avoid unnecessary_type_check warning.
      final Object obj = StrBox(count: 3, item: 'hello');
      require(obj is IBox, 'StrBox must implement IBox');
      final IBox ref = obj as IBox;
      require(ref.count == 3, 'count through IBox ref on StrBox must be 3');
    });

    test('IBox member set is exactly {count}', () {
      // Verify via static structural conformance: IBox declares `int get count`.
      // Instantiate a minimal anonymous implementor and read count.
      final IBox ref = IntBox(count: 5, item: 0);
      require(ref.count == 5, 'IBox.count getter must be present and readable');
    });
  });

  // ── Req 1: IMirroredPayload (mirror) — standalone; IntPayload NOT implements ──

  group('IMirroredPayload mirror', () {
    test('IntPayloadProbe is an IMirroredPayload', () {
      // Upcast to Object before `is` to avoid unnecessary_type_check warning.
      final Object obj = IntPayloadProbe(label: 'hello');
      require(obj is IMirroredPayload, 'IntPayloadProbe must implement IMirroredPayload');
    });

    test('IntPayloadProbe label readable through IMirroredPayload-typed reference', () {
      final IMirroredPayload ref = IntPayloadProbe(label: 'world');
      require(ref.label == 'world', 'label through IMirroredPayload ref must be "world"');
    });

    test('IntPayload does NOT implement IMirroredPayload (mirror is not wired onto host)', () {
      final obj = IntPayload(label: 'x', value: 1);
      require(obj is! IMirroredPayload,
          'IntPayload must NOT implement IMirroredPayload (mirror, not wired onto host)');
    });

    test('IMirroredPayload member set: label is declared', () {
      // Verified structurally: IMirroredPayload.label is a getter.
      final IMirroredPayload ref = IntPayloadProbe(label: 'check');
      require(ref.label == 'check', 'IMirroredPayload.label getter must be present and readable');
    });
  });

  // ── Req 5: ITagged (contract) / ITagMirror (mirror) — multiple clauses ────

  group('ITagged contract / ITagMirror mirror', () {
    test('IntTagged implements ITagged', () {
      // Upcast to Object before `is` to avoid unnecessary_type_check warning.
      final Object obj = IntTagged(label: 't', extra: 5);
      require(obj is ITagged, 'IntTagged must implement ITagged');
    });

    test('IntTagged label readable through ITagged-typed reference', () {
      final ITagged ref = IntTagged(label: 'tagged', extra: 0);
      require(ref.label == 'tagged', 'label through ITagged ref must be "tagged"');
    });

    test('IntTagged does NOT implement ITagMirror (mirror is standalone)', () {
      final obj = IntTagged(label: 't', extra: 0);
      require(obj is! ITagMirror,
          'IntTagged must NOT implement ITagMirror (mirror is not wired onto host)');
    });

    test('IntTagMirrorProbe implements ITagMirror', () {
      // Upcast to Object before `is` to avoid unnecessary_type_check warning.
      final Object obj = IntTagMirrorProbe(label: 'm');
      require(obj is ITagMirror, 'IntTagMirrorProbe must implement ITagMirror');
    });

    test('IntTagMirrorProbe label readable through ITagMirror-typed reference', () {
      final ITagMirror ref = IntTagMirrorProbe(label: 'mirror');
      require(ref.label == 'mirror', 'label through ITagMirror ref must be "mirror"');
    });

    test('ITagged member set: label is declared', () {
      final ITagged ref = IntTagged(label: 'tagcheck', extra: 0);
      require(ref.label == 'tagcheck', 'ITagged.label getter must be present');
    });

    test('ITagMirror member set: label is declared', () {
      final ITagMirror ref = IntTagMirrorProbe(label: 'mirrorcheck');
      require(ref.label == 'mirrorcheck', 'ITagMirror.label getter must be present');
    });
  });

  // ── Req 4: IKey (contract) — templated id host ────────────────────────────

  group('IKey contract', () {
    test('IntKey implements IKey', () {
      // Upcast to Object before `is` to avoid unnecessary_type_check warning.
      final Object obj = IntKey(key: 1, v: 2);
      require(obj is IKey, 'IntKey must implement IKey');
    });

    test('StrKey implements IKey (>=2 instantiations)', () {
      // Upcast to Object before `is` to avoid unnecessary_type_check warning.
      final Object obj = StrKey(key: 1, v: 'x');
      require(obj is IKey, 'StrKey must implement IKey');
    });

    test('IntKey key readable through IKey-typed reference', () {
      final IKey ref = IntKey(key: 99, v: 0);
      require(ref.key == 99, 'key through IKey ref must be 99');
    });

    test('IKey member set: key is declared', () {
      final IKey ref = IntKey(key: 5, v: 0);
      require(ref.key == 5, 'IKey.key getter must be present');
    });
  });

  // ── Req 3: IResult (contract) — ADT host ─────────────────────────────────

  group('IResult contract', () {
    test('Ok (IntResult branch) implements IResult', () {
      // Upcast to Object before `is` to avoid unnecessary_type_check warning.
      final Object obj = Ok(tag: 'ok', result: 1);
      require(obj is IResult, 'Ok must implement IResult');
    });

    test('Err (IntResult branch) implements IResult', () {
      // Upcast to Object before `is` to avoid unnecessary_type_check warning.
      final Object obj = Err(tag: 'err', msg: 'oops');
      require(obj is IResult, 'Err must implement IResult');
    });

    test('tag readable through IResult-typed reference', () {
      final IResult ref = Ok(tag: 'success', result: 42);
      require(ref.tag == 'success', 'tag through IResult ref must be "success"');
    });
  });

  // ── Req 6: IContainer (contract) — through-parent contribution ───────────

  group('IContainer contract', () {
    test('IntContainer implements IContainer', () {
      // Upcast to Object before `is` to avoid unnecessary_type_check warning.
      final Object obj = IntContainer(own: 1, item: 2, first: 3, second: 4, base_field: 5);
      require(obj is IContainer, 'IntContainer must implement IContainer');
    });

    test('IContainer members readable through typed reference', () {
      final IContainer ref = IntContainer(own: 10, item: 99, first: 0, second: 20, base_field: 30);
      require(ref.own == 10, 'own through IContainer ref must be 10');
      require(ref.second == 20, 'second through IContainer ref must be 20');
      require(ref.base_field == 30, 'base_field through IContainer ref must be 30');
    });

    test('IContainer member set: own, second, base_field declared', () {
      final IContainer ref = IntContainer(own: 1, item: 0, first: 0, second: 2, base_field: 3);
      require(ref.own == 1, 'IContainer.own getter must be present');
      require(ref.second == 2, 'IContainer.second getter must be present');
      require(ref.base_field == 3, 'IContainer.base_field getter must be present');
    });
  });
}
