// MFACADE-PR-6 stage B (ts): the codegen emits a `class DomainMyOkFacade extends
// BaboonCodecsFacade` per domain that auto-registers every known version in its ctor.
// Generated by `mdl :test-gen-regular-adt`.

import { describe, expect, test } from 'vitest';
import { BaboonCodecContext } from '../generated/BaboonSharedRuntime';
import { DomainMyOkFacade } from '../generated/my/ok/DomainMyOkFacade';
import { Inner } from '../generated/my/ok/Inner';

describe('DomainMyOkFacade', () => {
    test('parameterless ctor auto-registers and round-trips Inner', () => {
        const facade = new DomainMyOkFacade();
        const sample = new Inner(42);

        const encoded = facade.encodeToBin(BaboonCodecContext.Compact, sample);
        expect(encoded.tag).toBe('Right');
        const bytes = (encoded as { tag: 'Right'; value: Uint8Array }).value;

        const decoded = facade.decodeFromBin(bytes);
        expect(decoded.tag).toBe('Right');
        const value = (decoded as { tag: 'Right'; value: unknown }).value;
        expect(value).toEqual(sample);
    });
});
