// T204 / D45 regression (compile-time): the domain facade must be reachable
// THROUGH the generated directory barrel, not only via its direct module path.
// `DomainFacade.test.ts` imports the facade directly (../generated/my/ok/DomainMyOkFacade)
// and so does NOT catch D45 (the facade being dropped from my/ok/index.ts). This test
// imports it from the barrel index (../generated/my/ok) — if generateBarrels omits the
// facade re-export, this import does not resolve and `npm run build`
// (tsc --noEmit -p tsconfig.typecheck.json) fails. Generated by `mdl :test-gen-regular-adt`.

import { describe, expect, test } from 'vitest';
import { BaboonCodecContext } from '../generated/BaboonSharedRuntime';
// Import THROUGH the directory barrel (my/ok/index.ts), NOT the direct facade module.
import { DomainMyOkFacade } from '../generated/my/ok';
import { Inner } from '../generated/my/ok/Inner';

describe('DomainMyOkFacade via barrel (D45)', () => {
    test('facade is re-exported from the my/ok/index.ts barrel and round-trips', () => {
        const facade = new DomainMyOkFacade();
        const sample = new Inner(42);

        const encoded = facade.encodeToBin(BaboonCodecContext.Compact, sample);
        expect(encoded.tag).toBe('Right');
        const bytes = (encoded as { tag: 'Right'; value: Uint8Array }).value;

        const decoded = facade.decodeFromBin(bytes);
        expect(decoded.tag).toBe('Right');
        const value = (decoded as { tag: 'Right'; value: unknown }).value;
        expect(value).toEqual(sample);
    });
});
