// MFACADE-PR-D (rs): smoke test for the auto-emitted DomainMyOkFacade.
//
// Construction proves auto-registration ran without panic; full round-trip is exercised
// by the cross-language acceptance harness (mdl :test-acceptance), since the per-version
// `BaboonGeneratedDyn` wrappers required by `encode_to_bin` are private to the generated
// facade module. Generated by `mdl :test-gen-regular-adt`.

use baboon_rs_stub::my::ok::domain_myok_facade::DomainMyOkFacade;

#[test]
fn parameterless_ctor_auto_registers() {
    let facade = DomainMyOkFacade::new();
    let latest = facade
        .facade
        .latest("my.ok")
        .expect("latest('my.ok') must resolve after auto-registration");
    assert_eq!((latest.major, latest.minor, latest.patch), (1, 0, 0));
}
