// MFACADE-PR-E (rs): full round-trip test for the auto-emitted DomainMyOkFacade.
//
// PR-E lifted MFACADE-PR-D's smoke-only constraint by impl-ing `BaboonGeneratedDyn`
// directly on user types (rather than on a private wrapper struct), so external code
// can now pass `&inner` to `facade.facade.encode_to_bin(&ctx, &inner)` directly.
// Generated by `mdl :test-gen-regular-adt`.

use baboon_rs_stub::baboon_runtime::BaboonCodecContext;
use baboon_rs_stub::my::ok::domain_myok_facade::DomainMyOkFacade;
use baboon_rs_stub::my::ok::inner::Inner;

#[test]
fn parameterless_ctor_auto_registers() {
    let facade = DomainMyOkFacade::new();
    let latest = facade
        .facade
        .latest("my.ok")
        .expect("latest('my.ok') must resolve after auto-registration");
    assert_eq!((latest.major, latest.minor, latest.patch), (1, 0, 0));
}

#[test]
fn round_trips_inner_via_facade() {
    let facade = DomainMyOkFacade::new();
    let sample = Inner { x: 42 };
    let ctx = BaboonCodecContext::Compact;

    let bytes = facade
        .facade
        .encode_to_bin(&ctx, &sample)
        .expect("encode_to_bin must succeed");

    let decoded = facade
        .facade
        .decode_from_bin_bytes(&bytes)
        .expect("decode_from_bin_bytes must succeed");

    let decoded_inner = decoded
        .as_any()
        .downcast_ref::<Inner>()
        .expect("decoded value must downcast to Inner");
    assert_eq!(decoded_inner, &sample);
}
