name: Baboon Build

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # don't forget to update prepare-release and the includes below
        os: [ ubuntu-latest, macos-12, windows-2022, macos-14 ]
        #graalvm-version: [ '22.3.1' ]
        java-version: [ '17' ]
        include:
          - os: ubuntu-latest
            executable-suffix: ''
            native-build-args: --verbose -J-Xmx10g
          - os: macos-12
            executable-suffix: ''
            native-build-args: --verbose -J-Xmx13g
          - os: macos-14
            executable-suffix: ''
            native-build-args: --verbose -J-Xmx13g
          - os: windows-2022
            executable-suffix: '.exe'
            # e2e is disabled due to unstable docker step
            #e2e: false
            native-build-args: --verbose -J-Xmx10g
    steps:
    - uses: actions/checkout@v4
    - name: Set up GraalVM (Java ${{ matrix.java-version }})
      uses: graalvm/setup-graalvm@v1
      with:
        #version: '${{ matrix.graalvm-version }}'
        java-version: '${{ matrix.java-version }}'
        distribution: 'graalvm-community'
        components: 'native-image'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        cache: 'sbt'
        native-image-job-reports: true
    - if: matrix.os == 'macos-14'
      run: |
        brew install sbt
    - name: Run tests
      run: sbt test
    - name: Build NI
      run: sbt GraalVMNativeImage/packageBin
    - uses: actions/upload-artifact@v4
      with:
        name: native-image-${{ matrix.os }}
        path: |
          target/graalvm-native-image/**
    - name: Run test build
      shell: bash
      run: |
        target/graalvm-native-image/baboon \
          --model-dir ./src/test/resources/baboon/ \
          --output ./test/cs-stub/ConversionsTest/Generated \
          --test-output ./test/cs-stub/ConversionsTest/Generated/tests \
          --gen-tests
        cd ./test/cs-stub
        dotnet build
        dotnet test ConversionsTest/ConversionsTest.csproj
  prepare-release:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: native-image-ubuntu-latest
          path: tmp/baboon-linux-x64
      - uses: actions/download-artifact@v4
        with:
          name: native-image-macos-12
          path: tmp/baboon-mac-x64
      - uses: actions/download-artifact@v4
        with:
          name: native-image-macos-14
          path: tmp/baboon-mac-arm64
      - uses: actions/download-artifact@v4
        with:
          name: native-image-windows-2022
          path: tmp/baboon-windows-x64
      - name: Prepare layout
        run: |
          pushd .
          cd tmp/
          zip -r9 baboon-linux-x64.zip ./baboon-linux-x64/
          zip -r9 baboon-mac-x64.zip ./baboon-mac-x64/
          zip -r9 baboon-mac-arm64.zip ./baboon-mac-arm64/
          zip -r9 baboon-windows-x64.zip ./baboon-windows-x64/
          popd

          mkdir dist
          mv ./tmp/baboon-linux-x64/baboon dist/baboon-linux-x64
          mv ./tmp/baboon-mac-x64/baboon dist/baboon-mac-x64
          mv ./tmp/baboon-mac-arm64/baboon dist/baboon-mac-arm64
          mv ./tmp/baboon-windows-x64/baboon.exe dist/baboon-x64.exe

          mkdir dist-zip
          mv ./tmp/baboon-linux-x64.zip ./dist-zip/
          mv ./tmp/baboon-mac-x64.zip ./dist-zip/
          mv ./tmp/baboon-mac-arm64.zip ./dist-zip/
          mv ./tmp/baboon-windows-x64.zip ./dist-zip/
      - uses: softprops/action-gh-release@v2
        id: create-release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/**
            dist-zip/**
