# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, ]
        graalvm-version: [ '22.3.1' ]
        java-version: [ '17' ]
        include:
          - os: ubuntu-latest
            executable-suffix: ''
            native-build-args: --verbose -J-Xmx10g
          - os: macos-latest
            executable-suffix: ''
            native-build-args: --verbose -J-Xmx13g
    steps:
    - uses: actions/checkout@v3
    - name: Set up GraalVM (Java ${{ matrix.java-version }})
      uses: graalvm/setup-graalvm@v1
      with:
        version: '${{ matrix.graalvm-version }}'
        java-version: '${{ matrix.java-version }}'
        distribution: 'graalvm-community'
        components: 'native-image'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        cache: 'sbt'
    - name: Run tests
      run: sbt test GraalVMNativeImage/packageBin
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: native-image
        path: |
          target/graalvm-native-image/**
